### ISSUE TITLE
the code of CDR and GDA

### ISSUE THREAD

**Issue by ZhangYi0621** [xiaoyuxin1002/SAIS#1]
Hello! Thanks for your excellent work~
I'm interested in your work on the two biomedical datasets CDR and GDA, could  you share the relevant code?
Best wishes!

**Comment by xiaoyuxin1002** [comment]
Hi, thanks for your interest in our work!

To run our codes on the two biomedical datasets, you just need to go through the following steps:
1. Obtain the datasets from the corresponding websites and convert them into the same format as DocRED;
2. Comment out the part in test() in main.py that is used for evidence-based data augmentation and ensemble inference;
3. Adjust the hyperparameters and input arguments accordingly in prepare.sh, main.sh, and info.py.

**Comment by marcuslyz98** [comment]
Hi, I am also interested in using the model trained on docRED and testing its performance on the unseen CDR and GDA dataset, could you share how to do that and specifically which lines to comment out in main.py?
