### ISSUE TITLE
AttributeError: 'Info' object has no attribute 'index'

### ISSUE THREAD

**Issue by ady-yu** [xiaoyuxin1002/SAIS#2]
When running the code, it occurs the error about "AttributeError: 'Info' object has no attribute 'index'".
![image](https://user-images.githubusercontent.com/69707855/180928114-9d2e8ea2-e2ee-4553-b647-4636ef614112.png)

Besides, it can not reproduce the results presented in the paper. The result i get is 0.6110 on the dev dataset. How to reproduce your result.
![image](https://user-images.githubusercontent.com/69707855/180928302-54591432-a7dd-4ba1-8c4e-615846515b2c.png)

**Comment by xiaoyuxin1002** [comment]
Thank you very much for pointing out the bug! I have updated the codes accordingly.
Regarding the dev set performance, have you checked your hyperparameters and library version? You could also experiment with different seeds.
In addition, we provided a trained model where you can download it <a href="https://drive.google.com/drive/folders/1_xM8GdK0G5geYn0t4_L4ONOobLHSpznO?usp=sharing">here</a> and run the evaluation steps with it to reproduce our results.
