### ISSUE TITLE
Ign F1 on test dataset

### ISSUE THREAD

**Issue by jeongwonkwak** [xiaoyuxin1002/SAIS#3]
Hello. Thanks for your great work ! 
As far as I know, a label is needed when calculating Ign F1, but the test dataset doesn't have a label.
I'm curious about how you calculated Ign F1 on the test dataset, could you please let me know?
Thank you.

**Comment by xiaoyuxin1002** [comment]
Thank you for your interest in our paper!
To calculate Ign F1 on the DocRED test set, you need to upload the set of predicted relations to their official Codalab competition at [https://competitions.codalab.org/competitions/20717](url).
To calculate Ign F1 on the DocRED develop set, you can refer to the function `evaluate` at Line 79 in util.py

**Comment by jeongwonkwak** [comment]
Thanks for your quick reply :)
I checked the F1 on the test set in Codalab. 
but in order to check the Ign F1 on the test set, I have to store the overlapping (title,h,t,r) data in test set and train set as a file such as `dev_in_train.pkl` in `prepare.py.`
If so, can I save only the labels that are not in the train set from the results of the test set and upload them to Codalab?
Please correct me if I'm wrong.
Thank you.

**Comment by xiaoyuxin1002** [comment]
I think that Codalab will output both F1 and Ign F1 (which is named as `RE_ignore_annotated_F1`) at the same time, if you just upload the prediction output. 
You don't need to manually remove the test set outputs that are also in the train set.

**Comment by jeongwonkwak** [comment]
I found it. Thank you so much!
